### ISSUE TITLE
No sort available in previous bills

### ISSUE THREAD

**Issue by muzixa** [recursivetree/seat-billing#1]
As a title said, there are no sorting in previous bills tabs
and no alliance select menu.

![image](https://user-images.githubusercontent.com/2127645/177274645-c9cea406-1fc4-48c3-9803-603a9189bb95.png)

**Comment by recursivetree** [comment]
I'm investigating the issue and i'll fix it soon

**Comment by recursivetree** [comment]
will be fixed in 4.0.3
