### ISSUE TITLE
Menu icon is missing

### ISSUE THREAD

**Issue by muzixa** [recursivetree/seat-billing#2]
As a title said:
![image](https://user-images.githubusercontent.com/2127645/177274963-e35dbc9f-dd9f-4171-a589-a7103ec79451.png)

**Comment by recursivetree** [comment]
it renders properly for me.
![Bildschirmfoto 2022-09-03 um 20 21 13](https://user-images.githubusercontent.com/60423027/188283457-8744b23b-2fa3-42a3-8a0a-35a292a45855.png)

**Comment by recursivetree** [comment]
Actually, it was wrong. Now the icon appears as it always should have, but never did
