### ISSUE TITLE
Wrong link in seat setting

### ISSUE THREAD

**Issue by muzixa** [recursivetree/seat-billing#3]
Im understand it's just a joke
![image](https://user-images.githubusercontent.com/2127645/177275420-bc56645c-9df7-4cb3-9b9b-3d76930dd205.png)

**Comment by recursivetree** [comment]
sorry, I completely missed this issue because I was on holidays back in july. Yes, it is a joke. I had to but in a url while developing, but the github repo wasn't ready yet. Perfect spot for a rickroll right?

**Comment by recursivetree** [comment]
I fixed it, but it might take a while to be released. I won't make a release just for a link
